# PHP CircleCI 2.1 configuration file
version: 2.1

# ジョブ間で使い回す共通設定（テンプレート）の定義
executors:
  php-executor:
    parameters:
      php-version:
        type: string
    docker:
      - image: cimg/php:<< parameters.php-version >>-node
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD

# 各ステップの共通化
commands:
  run-tests:
    steps:
      - checkout
      # 先にキャッシュを戻す
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: Composer self-update
          command: |
            sudo composer self-update
      - run:
          name: Install dependencies
          command: |
            composer install -vvv
      # 後からキャッシュを保存する
      - save_cache:
          paths:
            - ~/.composer/cache
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: Install xdebug
          command: |
            sudo pecl install xdebug
      - run:
          name: Run tests
          command: |
            export XDEBUG_MODE=coverage
            vendor/bin/phpunit tests --exclude-group large

jobs:
  test82:
    executor:
      name: php-executor
      php-version: "8.2"
    working_directory: ~/repo82
    steps:
      - run-tests

  test83:
    executor:
      name: php-executor
      php-version: "8.3"
    working_directory: ~/repo83
    steps:
      - run-tests

  test84:
    executor:
      name: php-executor
      php-version: "8.4"
    working_directory: ~/repo84
    steps:
      - run-tests

  test85:
    executor:
      name: php-executor
      php-version: "8.5"
    working_directory: ~/repo85
    steps:
      - run-tests
workflows:
  tests:
    jobs:
      - test82:
          context:
            - dockerhub
      - test83:
          context:
            - dockerhub
      - test84:
          context:
            - dockerhub
      - test85:
          context:
            - dockerhub

