# PHP CircleCI 2.1 configuration file
version: 2.1

# ジョブ間で使い回す共通設定（テンプレート）の定義
executors:
  php-executor:
    parameters:
      php-version:
        type: string
    docker:
      - image: cimg/php:<< parameters.php-version >>-node
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD

# 各ステップの共通化
commands:
  run-tests:
    parameters:
      php-version:
        type: string
      with-coverage:
        type: boolean
        default: true
      with-bcmath-compat:
        type: boolean
        default: false
    steps:
      - checkout
      # 先にキャッシュを戻す
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: Composer self-update
          command: |
            sudo composer self-update --2
      - run:
          name: Install dependencies
          command: |
            composer install -vvv
      - when:
          condition: << parameters.with-bcmath-compat >>
          steps:
            - run:
                name: Install bcmath polyfill
                command: |
                  composer require phpseclib/bcmath_compat --no-interaction
      # 後からキャッシュを保存する
      - save_cache:
          paths:
            - ~/.composer/cache
          key: v1-dependencies-{{ checksum "composer.json" }}
      - when:
          condition: << parameters.with-coverage >>
          steps:
            - run:
                name: Install xdebug
                command: |
                  sudo pecl install xdebug
            - run:
                name: Run tests with coverage
                command: |
                  export XDEBUG_MODE=coverage
                  vendor/bin/phpunit tests --exclude-group long-running
      - unless:
          condition: << parameters.with-coverage >>
          steps:
            - run:
                name: Run tests without coverage
                command: |
                  vendor/bin/phpunit tests --exclude-group long-running

jobs:
  test72:
    executor:
      name: php-executor
      php-version: "7.2"
    working_directory: ~/repo72
    steps:
      - run-tests:
          php-version: "7.2"
          with-coverage: false
          with-bcmath-compat: true
  test80:
    executor:
      name: php-executor
      php-version: "8.0"
    working_directory: ~/repo80
    steps:
      - run-tests:
          php-version: "8.0"
  test81:
    executor:
      name: php-executor
      php-version: "8.1"
    working_directory: ~/repo81
    steps:
      - run-tests:
          php-version: "8.1"
  test82:
    executor:
      name: php-executor
      php-version: "8.2"
    working_directory: ~/repo82
    steps:
      - run-tests:
          php-version: "8.2"

  test83:
    executor:
      name: php-executor
      php-version: "8.3"
    working_directory: ~/repo83
    steps:
      - run-tests:
          php-version: "8.3"

  test84:
    executor:
      name: php-executor
      php-version: "8.4"
    working_directory: ~/repo84
    steps:
      - run-tests:
          php-version: "8.4"

  test85:
    executor:
      name: php-executor
      php-version: "8.5"
    working_directory: ~/repo85
    steps:
      - run-tests:
          php-version: "8.5"
workflows:
  tests:
    jobs:
      - test72:
          context:
            - dockerhub
      - test80:
          context:
            - dockerhub
      - test81:
          context:
            - dockerhub
      - test82:
          context:
            - dockerhub
      - test83:
          context:
            - dockerhub
      - test84:
          context:
            - dockerhub
      - test85:
          context:
            - dockerhub
